### ISSUE TITLE
执行 npx squash-cli 压缩图片抛错

### ISSUE THREAD

**Issue by QuocVi1994** [xccjk/squash-cli#1]
![image](https://user-images.githubusercontent.com/10477340/126525337-e79a3fb5-1053-46e6-bef2-9410f9becadf.png)

我的文件目录结构为 
```
| assets
--| img
| src
.... 其他配置文件
```

当我执行命令

> npx squash-cli --folder=img/ --md=true

后，抛错上述错误，看上去像是 squash-cli 对于异常状态的处理抛错

**Comment by xccjk** [comment]
你这个问题，应该是图片上传阶段网络原因导致上传失败，脚本中在解析图片上传返回的buffer时未做兼容处理导致的。主要错误原因：**tinyjpg.com:443**

你看看你是否可以在浏览器正常打开[tinyjpg.com](https://tinyjpg.com)，大概率是你那边网络本身被限制了。

同时我也添加了一个使用示例到github上了，可以clone下来本地跑一下。具体地址：[squash-cli examples](https://github.com/xccjk/squash-cli/tree/master/examples/app)

**Comment by QuocVi1994** [comment]
> 你这个问题，应该是图片上传阶段网络原因导致上传失败，脚本中在解析图片上传返回的buffer时未做兼容处理导致的。主要错误原因：**tinyjpg.com:443**
> 
> 你看看你是否可以在浏览器正常打开[tinyjpg.com](https://tinyjpg.com)，大概率是你那边网络本身被限制了。
> 
> 同时我也添加了一个使用示例到github上了，可以clone下来本地跑一下。具体地址：[squash-cli examples](https://github.com/xccjk/squash-cli/tree/master/examples/app)

多谢，后来确实可以了

**Comment by xccjk** [comment]
tinyjpg.com:443
